CREATE SCHEMA share_it;
SET SCHEMA 'share_it';

CREATE DOMAIN bla_bla_type VARCHAR (1000000);

CREATE TABLE city(
    name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE category(
    name VARCHAR (100) PRIMARY KEY
);

CREATE TABLE state(
    name VARCHAR (100) PRIMARY KEY
);